apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockndeploy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-dockndeploy
  template:
    metadata:
      labels:
        app: pod-dockndeploy
    spec:
      containers:
        - name: container-dockndeploy
          image: ghcr.io/nicoverflow/dockndeploy:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
       - name: gitlab-secret